import { SeoPage } from './types';

export const enPages: SeoPage[] = [
  {
    slug: 'manufacturing',
    title: 'Manufacturing SOP Generator — Create SOPs from Video | FrameOps',
    description: 'Turn manufacturing floor videos into professional SOPs automatically. Film assembly lines, machine operations, and quality checks — AI creates step-by-step procedures with screenshots.',
    keywords: 'manufacturing SOP generator, factory SOP software, assembly line documentation, manufacturing work instructions, production SOP template, quality control SOP',
    h1: 'Manufacturing SOP Generator',
    intro: 'Transform manufacturing floor videos into professional standard operating procedures. Film machine operations, assembly processes, and quality inspections — FrameOps AI automatically creates step-by-step SOPs with annotated screenshots.',
    howItWorks: [
      'Film the manufacturing process with your phone or any camera',
      'Upload the video to FrameOps — AI detects each step automatically',
      'Review and edit the generated SOP with screenshots from the video',
      'Export as PDF, share digitally, or print for the shop floor',
    ],
    faq: [
      { question: 'Can FrameOps handle noisy factory environments?', answer: 'Yes. FrameOps uses advanced audio processing and scene detection, so even in noisy manufacturing environments the AI accurately identifies each step from the video.' },
      { question: 'What manufacturing processes work best?', answer: 'Assembly, machine setup, quality inspection, packaging, maintenance procedures, and changeover processes all work great. Any visual, step-by-step task can be documented.' },
      { question: 'Can I add safety warnings to manufacturing SOPs?', answer: 'Absolutely. FrameOps automatically detects PPE and safety-related steps, and you can add custom safety warnings, caution notices, and required equipment lists.' },
    ],
  },
  {
    slug: 'healthcare',
    title: 'Healthcare SOP Generator — Medical Procedure Documentation | FrameOps',
    description: 'Create healthcare SOPs from video recordings. Document medical procedures, nursing protocols, and clinical workflows automatically with AI-powered step detection.',
    keywords: 'healthcare SOP generator, medical procedure documentation, nursing SOP software, clinical workflow documentation, hospital SOP template, patient care procedures',
    h1: 'Healthcare SOP Generator',
    intro: 'Document healthcare procedures and clinical workflows by filming them. FrameOps AI watches the video and creates detailed, compliant standard operating procedures with clear step-by-step instructions and visual references.',
    howItWorks: [
      'Record the clinical procedure or workflow on video',
      'Upload to FrameOps — AI identifies each procedural step',
      'Review the generated SOP and add compliance notes',
      'Export and distribute to clinical staff',
    ],
    faq: [
      { question: 'Is FrameOps suitable for clinical SOPs?', answer: 'Yes. FrameOps generates structured documentation that can be reviewed and approved by clinical staff. The output format supports compliance requirements for healthcare documentation.' },
      { question: 'Can I document nursing procedures?', answer: 'Absolutely. Film any nursing procedure — wound care, medication administration, patient transfer — and FrameOps creates a detailed SOP with screenshots from the video.' },
      { question: 'Does it handle hygiene and safety protocols?', answer: 'Yes. The AI detects hand washing, glove changes, and other hygiene steps. You can also add custom safety and hygiene notes to any step.' },
    ],
  },
  {
    slug: 'food-safety',
    title: 'Food Safety SOP Generator — HACCP Documentation from Video | FrameOps',
    description: 'Generate food safety SOPs and HACCP documentation from video. Film kitchen procedures, food handling, and sanitation processes — AI creates compliant step-by-step guides.',
    keywords: 'food safety SOP generator, HACCP documentation software, kitchen SOP template, food handling procedures, restaurant SOP generator, sanitation SOP',
    h1: 'Food Safety SOP Generator',
    intro: 'Create food safety and HACCP-compliant SOPs by filming your kitchen and food handling procedures. FrameOps AI automatically documents each step with screenshots, making compliance documentation fast and visual.',
    howItWorks: [
      'Film food preparation, handling, or sanitation procedures',
      'Upload the video — AI breaks it into clear steps',
      'Add HACCP critical control points and temperature requirements',
      'Export compliant documentation for audits and training',
    ],
    faq: [
      { question: 'Can I use this for HACCP documentation?', answer: 'Yes. FrameOps creates structured step-by-step procedures that can serve as the basis for HACCP plans. You can add critical control points, limits, and monitoring procedures to each step.' },
      { question: 'Does it work for restaurant kitchens?', answer: 'Absolutely. Film any kitchen procedure — prep, cooking, cleaning, receiving — and get a professional SOP. Perfect for training new kitchen staff.' },
      { question: 'Can I document cleaning and sanitation procedures?', answer: 'Yes. Sanitation SOPs are one of the most common use cases. Film the cleaning process and get a step-by-step guide with chemical concentrations, contact times, and visual checkpoints.' },
    ],
  },
  {
    slug: 'construction',
    title: 'Construction SOP Generator — Site Procedure Documentation | FrameOps',
    description: 'Create construction SOPs from job site videos. Document safety procedures, equipment operation, and work methods automatically with AI-generated step-by-step guides.',
    keywords: 'construction SOP generator, job site documentation, construction safety procedures, equipment operation SOP, construction work instructions, site safety documentation',
    h1: 'Construction SOP Generator',
    intro: 'Document construction procedures and safety protocols by filming them on-site. FrameOps AI creates professional SOPs with step-by-step instructions and visual references from your job site videos.',
    howItWorks: [
      'Film the construction procedure or safety process on-site',
      'Upload to FrameOps — AI identifies each step and safety requirement',
      'Review and add site-specific safety warnings',
      'Distribute to crews as PDF or digital guides',
    ],
    faq: [
      { question: 'Can I film in outdoor construction environments?', answer: 'Yes. FrameOps works with any video quality. Film with your phone on the job site — the AI handles varying lighting, wind noise, and outdoor conditions.' },
      { question: 'Does it detect safety equipment in videos?', answer: 'FrameOps identifies PPE usage and safety-related steps. You can add hard hat, harness, and other safety requirements to each step of the SOP.' },
      { question: 'Can I use it for equipment operation procedures?', answer: 'Absolutely. Film equipment startup, operation, and shutdown procedures. The AI creates detailed operator guides with screenshots from the video.' },
    ],
  },
  {
    slug: 'automotive',
    title: 'Automotive SOP Generator — Workshop & Assembly Documentation | FrameOps',
    description: 'Generate automotive SOPs from video. Document repair procedures, assembly processes, and workshop operations with AI-powered step-by-step guides and screenshots.',
    keywords: 'automotive SOP generator, workshop documentation, car repair SOP, assembly procedure documentation, automotive work instructions, vehicle maintenance SOP',
    h1: 'Automotive SOP Generator',
    intro: 'Create professional automotive SOPs by filming repair, assembly, and maintenance procedures. FrameOps AI transforms workshop videos into clear step-by-step guides with tool lists and annotated screenshots.',
    howItWorks: [
      'Film the automotive procedure — repair, assembly, or maintenance',
      'Upload the video and let AI detect each step',
      'Review the SOP with tool requirements and torque specs',
      'Export for technician training or workshop reference',
    ],
    faq: [
      { question: 'Can I document complex repair procedures?', answer: 'Yes. FrameOps handles multi-step repair procedures well. The AI detects tool changes, part removal/installation, and creates detailed sequences with visual references.' },
      { question: 'Does it identify tools used in the video?', answer: 'FrameOps detects common tools and equipment. You can also add specific tool requirements, part numbers, and torque specifications to each step.' },
      { question: 'Can I use it for vehicle inspection checklists?', answer: 'Absolutely. Film the inspection process and FrameOps creates a visual checklist with screenshots of each inspection point.' },
    ],
  },
  {
    slug: 'warehouse',
    title: 'Warehouse SOP Generator — Logistics & Fulfillment Documentation | FrameOps',
    description: 'Create warehouse SOPs from video. Document picking, packing, receiving, and shipping procedures with AI-generated step-by-step guides and visual references.',
    keywords: 'warehouse SOP generator, logistics documentation, fulfillment SOP, picking packing procedures, warehouse work instructions, shipping SOP template',
    h1: 'Warehouse SOP Generator',
    intro: 'Document warehouse operations by filming them. FrameOps AI turns videos of picking, packing, receiving, and shipping into professional SOPs with clear visual instructions for warehouse staff.',
    howItWorks: [
      'Film warehouse processes — picking routes, packing, receiving',
      'Upload to FrameOps — AI creates step-by-step procedures',
      'Add warehouse-specific details like bin locations and scan points',
      'Share with warehouse teams for consistent operations',
    ],
    faq: [
      { question: 'Can I document picking and packing procedures?', answer: 'Yes. Film the entire pick-pack-ship workflow and FrameOps creates a visual SOP showing each station, scan point, and quality check.' },
      { question: 'Does it work for forklift and equipment operations?', answer: 'Absolutely. Film equipment operation procedures and get SOPs with safety checks, load limits, and step-by-step operation guides.' },
      { question: 'Can I create receiving and shipping SOPs?', answer: 'Yes. Document dock procedures, receiving inspections, and shipping processes. The AI captures each checkpoint and creates clear, visual procedures.' },
    ],
  },
  {
    slug: 'it-operations',
    title: 'IT Operations SOP Generator — IT Procedure Documentation | FrameOps',
    description: 'Create IT operations SOPs from screen recordings and videos. Document server procedures, network setup, and IT workflows with AI-generated step-by-step guides.',
    keywords: 'IT SOP generator, IT operations documentation, server procedure SOP, network setup documentation, IT workflow documentation, helpdesk SOP template',
    h1: 'IT Operations SOP Generator',
    intro: 'Document IT procedures by recording your screen or filming hardware tasks. FrameOps AI creates detailed IT SOPs with screenshots, making knowledge transfer and incident response documentation effortless.',
    howItWorks: [
      'Record your screen or film the IT procedure',
      'Upload to FrameOps — AI detects each configuration step',
      'Review with command details and screenshots',
      'Share with IT team or use for onboarding',
    ],
    faq: [
      { question: 'Can I use screen recordings for IT SOPs?', answer: 'Yes. FrameOps works with screen recordings, so you can document software installations, server configurations, and admin panel procedures with full screenshot capture.' },
      { question: 'Does it handle command-line procedures?', answer: 'FrameOps captures command-line sessions from screen recordings and creates step-by-step guides showing each command and its expected output.' },
      { question: 'Can I document network and server procedures?', answer: 'Absolutely. Film physical hardware tasks or record screen for software configuration. FrameOps creates comprehensive IT runbooks with visual references.' },
    ],
  },
  {
    slug: 'onboarding',
    title: 'Employee Onboarding SOP Generator — Training Documentation | FrameOps',
    description: 'Create onboarding SOPs from video. Film training sessions and daily procedures — AI generates step-by-step guides for new employee orientation and skill development.',
    keywords: 'onboarding SOP generator, employee training documentation, new hire training guide, onboarding procedure template, training manual generator, employee orientation SOP',
    h1: 'Employee Onboarding SOP Generator',
    intro: 'Build onboarding and training materials by filming how tasks are done. FrameOps AI creates visual step-by-step guides that new employees can follow from day one — reducing training time and ensuring consistency.',
    howItWorks: [
      'Film experienced employees performing key tasks',
      'Upload videos — AI creates training guides for each procedure',
      'Organize guides into onboarding sequences',
      'New hires follow visual SOPs for faster ramp-up',
    ],
    faq: [
      { question: 'How does this speed up onboarding?', answer: 'Instead of shadowing experienced workers for weeks, new hires get visual step-by-step guides they can follow independently. Companies typically reduce training time by 50% or more.' },
      { question: 'Can I create a complete onboarding package?', answer: 'Yes. Film all key procedures and FrameOps creates individual SOPs. Organize them into a training sequence for a complete onboarding program.' },
      { question: 'Does it work for both physical and digital tasks?', answer: 'Absolutely. Film hands-on tasks with your phone or record screen for software procedures. FrameOps handles both types seamlessly.' },
    ],
  },
  {
    slug: 'maintenance',
    title: 'Maintenance SOP Generator — Equipment Maintenance Documentation | FrameOps',
    description: 'Create maintenance SOPs from video. Film equipment maintenance, preventive checks, and repair procedures — AI generates detailed work instructions with visual references.',
    keywords: 'maintenance SOP generator, equipment maintenance documentation, preventive maintenance SOP, repair procedure guide, maintenance work instructions, PM checklist generator',
    h1: 'Maintenance SOP Generator',
    intro: 'Document equipment maintenance procedures by filming them. FrameOps AI creates detailed maintenance SOPs with step-by-step instructions, tool requirements, and visual checkpoints for preventive and corrective maintenance.',
    howItWorks: [
      'Film the maintenance procedure — PM, repair, or inspection',
      'Upload to FrameOps — AI breaks it into detailed steps',
      'Add part numbers, intervals, and safety requirements',
      'Use as maintenance manuals or PM checklists',
    ],
    faq: [
      { question: 'Can I create preventive maintenance checklists?', answer: 'Yes. Film the PM procedure and FrameOps creates a visual checklist with each inspection point, lubrication step, and measurement captured as a step with a screenshot.' },
      { question: 'Does it work for complex equipment?', answer: 'Absolutely. FrameOps handles multi-step procedures on complex machinery. The AI detects tool changes, disassembly steps, and reassembly sequences.' },
      { question: 'Can I include part numbers and specifications?', answer: 'Yes. After the AI generates the base SOP, you can add part numbers, torque specs, fluid capacities, and other technical details to each step.' },
    ],
  },
  {
    slug: 'field-service',
    title: 'Field Service SOP Generator — Mobile Procedure Documentation | FrameOps',
    description: 'Create field service SOPs from video. Film on-site installations, repairs, and inspections with your phone — AI generates mobile-friendly step-by-step guides for technicians.',
    keywords: 'field service SOP generator, mobile procedure documentation, technician work instructions, on-site installation guide, field service manual, service call documentation',
    h1: 'Field Service SOP Generator',
    intro: 'Document field service procedures by filming them on-site with your phone. FrameOps AI creates mobile-friendly SOPs that technicians can follow during installations, repairs, and inspections — ensuring consistency across all service calls.',
    howItWorks: [
      'Film the field service procedure on-site with your phone',
      'Upload to FrameOps — AI creates a mobile-friendly SOP',
      'Add troubleshooting notes and parts information',
      'Technicians access SOPs on their mobile devices',
    ],
    faq: [
      { question: 'Can technicians use SOPs on mobile?', answer: 'Yes. FrameOps SOPs are designed to be mobile-friendly. Technicians can access step-by-step guides with screenshots on their phones or tablets during service calls.' },
      { question: 'Does it work for installation procedures?', answer: 'Absolutely. Film the installation process and FrameOps creates a complete installation guide with visual references, tool requirements, and connection diagrams.' },
      { question: 'Can I document troubleshooting procedures?', answer: 'Yes. Film the troubleshooting process and create decision-tree style SOPs that guide technicians through diagnosis and repair steps.' },
    ],
  },
  {
    slug: 'video-to-sop',
    title: 'Video to SOP Converter — Turn Any Video into a Step-by-Step Guide | FrameOps',
    description: 'Convert any video into a professional SOP automatically. Upload a video file, FrameOps AI detects steps, captures screenshots, and generates a complete standard operating procedure.',
    keywords: 'video to SOP converter, turn video into SOP, video to work instructions, convert video to guide, video to procedure, automatic SOP from video',
    h1: 'Video to SOP Converter',
    intro: 'Upload any video and get a professional SOP in minutes. FrameOps AI watches your video, detects each step, captures key frames as screenshots, and writes clear instructions — transforming hours of documentation work into a simple upload.',
    howItWorks: [
      'Upload any video file — MP4, MOV, AVI, or other formats',
      'AI analyzes the video: detects steps, captures screenshots, transcribes audio',
      'Review the auto-generated SOP with step-by-step instructions',
      'Export as PDF or share digitally with your team',
    ],
    faq: [
      { question: 'What video formats are supported?', answer: 'FrameOps supports all common video formats including MP4, MOV, AVI, and WebM. You can also paste a YouTube URL to convert online videos.' },
      { question: 'How accurate is the step detection?', answer: 'FrameOps uses advanced scene detection and audio analysis to identify steps with high accuracy. You can always adjust, split, or merge steps in the editor.' },
      { question: 'Can I edit the generated SOP?', answer: 'Yes. The AI generates a complete first draft that you can edit — change text, reorder steps, add or remove screenshots, and insert safety warnings or notes.' },
    ],
  },
  {
    slug: 'screen-recording-sop',
    title: 'Screen Recording to SOP — Turn Screen Captures into Guides | FrameOps',
    description: 'Record your screen and get a step-by-step SOP automatically. Perfect for software tutorials, IT procedures, and digital workflows. AI detects clicks and actions.',
    keywords: 'screen recording to SOP, screen capture to guide, software tutorial generator, IT procedure documentation, screen recording to manual, digital workflow SOP',
    h1: 'Screen Recording to SOP Generator',
    intro: 'Record your screen and FrameOps AI turns it into a professional step-by-step guide. Perfect for documenting software procedures, IT workflows, and digital processes — every click and action becomes a clear instruction with a screenshot.',
    howItWorks: [
      'Record your screen while performing the procedure',
      'Upload the recording to FrameOps',
      'AI detects each click, navigation, and action as separate steps',
      'Get a polished SOP with annotated screenshots',
    ],
    faq: [
      { question: 'Does it capture individual clicks as steps?', answer: 'Yes. FrameOps AI detects screen changes, clicks, and navigation actions, creating a separate step for each meaningful action in the recording.' },
      { question: 'Can I use it for software training?', answer: 'Absolutely. Screen recording SOPs are perfect for onboarding new employees to software tools, creating help desk guides, and documenting IT procedures.' },
      { question: 'Does it work with any screen recorder?', answer: 'Yes. Use any screen recording tool you prefer. FrameOps works with the video file output — MP4, MOV, WebM, or any common format.' },
    ],
  },
  {
    slug: 'youtube-to-guide',
    title: 'YouTube to Guide Converter — Turn YouTube Videos into Step-by-Step Guides | FrameOps',
    description: 'Convert YouTube videos into professional step-by-step guides. Paste a URL, FrameOps AI extracts steps and screenshots automatically. Perfect for content creators and educators.',
    keywords: 'YouTube to guide, YouTube to SOP, convert YouTube video to instructions, YouTube tutorial to PDF, video to step by step guide, YouTube to documentation',
    h1: 'YouTube to Step-by-Step Guide Converter',
    intro: 'Paste a YouTube URL and get a professional step-by-step guide in minutes. FrameOps AI watches the video, identifies each step, captures key frames, and writes clear instructions — perfect for repurposing tutorials into downloadable guides.',
    howItWorks: [
      'Paste any YouTube video URL into FrameOps',
      'AI downloads and analyzes the video automatically',
      'Review the generated guide with screenshots from the video',
      'Export as PDF to share or offer as a lead magnet',
    ],
    faq: [
      { question: 'Can I use any YouTube video?', answer: 'You can use any public YouTube video. For best results, use tutorial-style or how-to videos where clear steps are demonstrated.' },
      { question: 'Is this good for content creators?', answer: 'Yes. Content creators use FrameOps to turn their YouTube tutorials into downloadable PDF guides — perfect as lead magnets, paid products, or bonus content for followers.' },
      { question: 'Does it capture the audio narration?', answer: 'Yes. FrameOps transcribes the audio and uses both visual and audio cues to create accurate step-by-step instructions.' },
    ],
  },
  {
    slug: 'tutorial-creator',
    title: 'Tutorial Creator — Generate Professional Tutorials from Video | FrameOps',
    description: 'Create professional tutorials from video automatically. Film or record a process, AI generates a polished tutorial with screenshots and clear instructions. No writing needed.',
    keywords: 'tutorial creator, tutorial generator from video, create tutorial automatically, how-to guide maker, tutorial maker AI, video to tutorial converter',
    h1: 'AI Tutorial Creator',
    intro: 'Create professional tutorials without writing a single word. Film or record any process and FrameOps AI generates a polished tutorial with numbered steps, screenshots, and clear instructions — ready to publish or share.',
    howItWorks: [
      'Film or screen-record the process you want to teach',
      'Upload to FrameOps — AI creates a structured tutorial',
      'Customize the layout, add tips, and refine the text',
      'Publish or export as PDF for your audience',
    ],
    faq: [
      { question: 'What kinds of tutorials can I create?', answer: 'Any process that can be filmed or screen-recorded: software tutorials, DIY projects, cooking recipes, craft instructions, repair guides, and more.' },
      { question: 'Can I brand the tutorials?', answer: 'Yes. Customize colors, add your logo, and adjust the layout to match your brand before exporting.' },
      { question: 'Is the output professional enough to sell?', answer: 'Absolutely. FrameOps generates clean, well-structured tutorials with high-quality screenshots that are ready for publication, courses, or paid downloads.' },
    ],
  },
  {
    slug: 'safety-training',
    title: 'Safety Training SOP Generator — Create Safety Procedures from Video | FrameOps',
    description: 'Create safety training SOPs from video. Film safety procedures, PPE usage, and emergency protocols — AI generates visual safety guides with warnings and compliance notes.',
    keywords: 'safety training SOP generator, safety procedure documentation, PPE training guide, emergency procedure SOP, workplace safety documentation, safety manual generator',
    h1: 'Safety Training SOP Generator',
    intro: 'Document safety procedures by filming them. FrameOps AI creates visual safety training SOPs with step-by-step instructions, PPE requirements, and safety warnings — making compliance training clear and consistent for every worker.',
    howItWorks: [
      'Film safety procedures, PPE protocols, or emergency drills',
      'Upload to FrameOps — AI identifies each safety step',
      'Add hazard warnings, PPE requirements, and compliance notes',
      'Distribute visual safety guides to all workers',
    ],
    faq: [
      { question: 'Can I add safety warnings to each step?', answer: 'Yes. FrameOps lets you add danger, warning, and caution notices to any step. The AI also automatically flags steps that involve PPE or safety-critical actions.' },
      { question: 'Does it work for emergency procedures?', answer: 'Absolutely. Film emergency evacuation routes, fire extinguisher usage, spill response, or first aid procedures and get clear visual guides.' },
      { question: 'Can I use it for safety compliance audits?', answer: 'Yes. The generated SOPs serve as documented evidence of standardized safety procedures, supporting ISO, OSHA, and other compliance requirements.' },
    ],
  },
];
