import { SeoPage } from './types';

export const svPages: SeoPage[] = [
  {
    slug: 'tillverkning',
    title: 'Skapa manualer för tillverkning — Filma och dokumentera | Manualen.nu',
    description: 'Förvandla tillverkningsvideor till professionella manualer automatiskt. Filma maskiner, monteringsprocesser och kvalitetskontroller — AI skapar steg-för-steg-instruktioner.',
    keywords: 'tillverkning manual, SOP tillverkning, skapa manual från video, fabrik dokumentation, monteringsinstruktion, kvalitetskontroll manual',
    h1: 'Skapa manualer för tillverkning',
    intro: 'Dokumentera tillverkningsprocesser genom att filma dem. AI:n tittar på videon och skapar professionella steg-för-steg-manualer med skärmdumpar — perfekt för maskindrift, montering och kvalitetskontroll.',
    howItWorks: [
      'Filma tillverkningsprocessen med din mobil eller kamera',
      'Ladda upp videon — AI:n identifierar varje steg automatiskt',
      'Granska och redigera manualen med bilder från videon',
      'Exportera som PDF eller dela digitalt med teamet',
    ],
    faq: [
      { question: 'Fungerar det i bullriga fabriksmiljöer?', answer: 'Ja. AI:n använder avancerad ljudbearbetning och scendetektering, så även i bullriga miljöer identifieras varje steg korrekt från videon.' },
      { question: 'Vilka tillverkningsprocesser fungerar bäst?', answer: 'Montering, maskininstallation, kvalitetskontroll, förpackning, underhåll och omställning fungerar utmärkt. Alla visuella steg-för-steg-uppgifter kan dokumenteras.' },
      { question: 'Kan jag lägga till säkerhetsvarningar?', answer: 'Absolut. AI:n upptäcker steg som rör skyddsutrustning och säkerhet, och du kan lägga till egna varningar och krav på utrustning.' },
    ],
  },
  {
    slug: 'sjukvard',
    title: 'Skapa manualer för sjukvård — Dokumentera vårdprocedurer | Manualen.nu',
    description: 'Skapa sjukvårdsmanualer från video. Dokumentera medicinska procedurer, omvårdnadsrutiner och kliniska arbetsflöden automatiskt med AI-genererade steg-för-steg-guider.',
    keywords: 'sjukvård manual, vårdprocedur dokumentation, omvårdnad SOP, kliniskt arbetsflöde, sjukhus manual, patientvård instruktion',
    h1: 'Skapa manualer för sjukvård',
    intro: 'Dokumentera vårdprocedurer och kliniska arbetsflöden genom att filma dem. AI:n skapar detaljerade steg-för-steg-manualer med tydliga instruktioner och visuella referenser.',
    howItWorks: [
      'Filma den kliniska proceduren eller arbetsflödet',
      'Ladda upp till Manualen.nu — AI:n identifierar varje steg',
      'Granska manualen och lägg till kvalitetskrav',
      'Exportera och distribuera till vårdpersonal',
    ],
    faq: [
      { question: 'Passar det för kliniska manualer?', answer: 'Ja. Manualen.nu genererar strukturerad dokumentation som kan granskas och godkännas av klinisk personal. Formatet stödjer kvalitetskrav inom vården.' },
      { question: 'Kan jag dokumentera omvårdnadsprocedurer?', answer: 'Absolut. Filma omvårdnad som sårvård, läkemedelshantering eller patientförflyttning och få en detaljerad manual med bilder.' },
      { question: 'Hanteras hygienrutiner?', answer: 'Ja. AI:n identifierar handtvätt, handskkbyten och andra hygienmoment. Du kan också lägga till egna hygienanvisningar.' },
    ],
  },
  {
    slug: 'livsmedel',
    title: 'Skapa manualer för livsmedelssäkerhet — HACCP-dokumentation | Manualen.nu',
    description: 'Skapa livsmedelsmanualer och HACCP-dokumentation från video. Filma köksrutiner och livsmedelshantering — AI genererar steg-för-steg-guider för livsmedelssäkerhet.',
    keywords: 'livsmedel manual, HACCP dokumentation, köks SOP, livsmedelshantering, restaurang manual, livsmedelssäkerhet guide',
    h1: 'Skapa manualer för livsmedelssäkerhet',
    intro: 'Dokumentera livsmedelshantering och HACCP-rutiner genom att filma ditt köksarbete. AI:n skapar steg-för-steg-manualer med bilder — snabb och visuell dokumentation för revision och utbildning.',
    howItWorks: [
      'Filma livsmedelshantering, tillagning eller städrutiner',
      'Ladda upp videon — AI:n delar upp i tydliga steg',
      'Lägg till HACCP-kontrollpunkter och temperaturkrav',
      'Exportera för revisioner och personalutbildning',
    ],
    faq: [
      { question: 'Kan jag använda det för HACCP-dokumentation?', answer: 'Ja. Manualen.nu skapar strukturerade steg-för-steg-procedurer som kan användas som underlag i HACCP-planer. Du kan lägga till kritiska kontrollpunkter och gränsvärden.' },
      { question: 'Fungerar det i restaurangkök?', answer: 'Absolut. Filma vilken köksrutin som helst — förberedelse, tillagning, städning, mottagning — och få en professionell manual.' },
      { question: 'Kan jag dokumentera städ- och sanitetsrutiner?', answer: 'Ja. Sanitetsrutiner är ett av de vanligaste användningsområdena. Filma städprocessen och få en guide med kemikalier, kontakttider och kontrollpunkter.' },
    ],
  },
  {
    slug: 'bygg',
    title: 'Skapa manualer för byggbranschen — Dokumentera arbetsmoment | Manualen.nu',
    description: 'Skapa bygg-manualer från arbetsplatsvideor. Dokumentera säkerhetsrutiner, maskinanvändning och arbetsmetoder med AI-genererade steg-för-steg-guider.',
    keywords: 'bygg manual, byggarbetsplats dokumentation, säkerhetsrutiner bygg, maskinanvändning guide, arbetsinstruktion bygg, byggsäkerhet SOP',
    h1: 'Skapa manualer för byggbranschen',
    intro: 'Dokumentera byggarbetsmoment och säkerhetsrutiner genom att filma dem på plats. AI:n skapar professionella manualer med steg-för-steg-instruktioner och bilder från arbetsplatsen.',
    howItWorks: [
      'Filma arbetsmoment eller säkerhetsrutiner på byggarbetsplatsen',
      'Ladda upp till Manualen.nu — AI:n identifierar varje steg',
      'Granska och lägg till platsspecifika säkerhetsvarningar',
      'Dela ut till arbetslag som PDF eller digitala guider',
    ],
    faq: [
      { question: 'Kan jag filma utomhus på bygget?', answer: 'Ja. Manualen.nu fungerar med alla videokvaliteter. Filma med mobilen på arbetsplatsen — AI:n hanterar varierande ljus, vind och utomhusförhållanden.' },
      { question: 'Identifieras skyddsutrustning?', answer: 'AI:n upptäcker användning av skyddsutrustning och säkerhetsrelaterade steg. Du kan lägga till krav på hjälm, sele och annan utrustning.' },
      { question: 'Fungerar det för maskininstruktioner?', answer: 'Absolut. Filma uppstart, drift och avstängning av maskiner och få detaljerade instruktioner med bilder.' },
    ],
  },
  {
    slug: 'lager',
    title: 'Skapa manualer för lager och logistik — Dokumentera lagerrutiner | Manualen.nu',
    description: 'Skapa lagermanualer från video. Dokumentera plockning, packning, mottagning och leverans med AI-genererade steg-för-steg-guider för lagerpersonal.',
    keywords: 'lager manual, logistik dokumentation, plockning packning SOP, lagerrutin guide, lagerpersonal instruktion, leverans manual',
    h1: 'Skapa manualer för lager och logistik',
    intro: 'Dokumentera lagerverksamheten genom att filma. AI:n förvandlar videor av plockning, packning, mottagning och leverans till professionella manualer med tydliga visuella instruktioner.',
    howItWorks: [
      'Filma lagerprocesser — plockrundor, packning, mottagning',
      'Ladda upp till Manualen.nu — AI:n skapar steg-för-steg-manualer',
      'Lägg till lagerspecifika detaljer som platsreferenser',
      'Dela med lagerpersonalen för konsekventa rutiner',
    ],
    faq: [
      { question: 'Kan jag dokumentera plock- och packrutiner?', answer: 'Ja. Filma hela plock-pack-skicka-flödet och få en visuell manual som visar varje station, scanpunkt och kvalitetskontroll.' },
      { question: 'Fungerar det för truckoperationer?', answer: 'Absolut. Filma truckoperationer och få manualer med säkerhetskontroller, lastgränser och steg-för-steg-instruktioner.' },
      { question: 'Kan jag skapa mottagar- och leveransmanualer?', answer: 'Ja. Dokumentera kajtrutiner, mottagningsinspektioner och leveransprocesser med tydliga kontrollpunkter.' },
    ],
  },
  {
    slug: 'it-drift',
    title: 'Skapa manualer för IT-drift — Dokumentera IT-procedurer | Manualen.nu',
    description: 'Skapa IT-manualer från skärminspelningar och video. Dokumentera serverrutiner, nätverkskonfiguration och IT-arbetsflöden med AI-genererade steg-för-steg-guider.',
    keywords: 'IT manual, IT-drift dokumentation, server procedur, nätverkskonfiguration guide, IT arbetsflöde manual, helpdesk SOP',
    h1: 'Skapa manualer för IT-drift',
    intro: 'Dokumentera IT-procedurer genom skärminspelning eller videoinspelning. AI:n skapar detaljerade IT-manualer med skärmbilder — perfekt för kunskapsöverföring och incidenthantering.',
    howItWorks: [
      'Spela in din skärm eller filma IT-proceduren',
      'Ladda upp till Manualen.nu — AI:n identifierar varje steg',
      'Granska med kommandodetaljer och skärmbilder',
      'Dela med IT-teamet eller använd vid onboarding',
    ],
    faq: [
      { question: 'Kan jag använda skärminspelningar?', answer: 'Ja. Manualen.nu fungerar med skärminspelningar, så du kan dokumentera mjukvaruinstallationer, serverkonfigurationer och adminpaneler med skärmbilder.' },
      { question: 'Hanteras kommandoradsoperationer?', answer: 'AI:n fångar kommandoradsessioner från skärminspelningar och skapar guider som visar varje kommando och förväntat resultat.' },
      { question: 'Kan jag dokumentera nätverks- och serverprocedurer?', answer: 'Absolut. Filma fysiska hårdvaruuppgifter eller spela in skärm för konfiguration. Du får kompletta IT-runbooks med visuella referenser.' },
    ],
  },
  {
    slug: 'onboarding',
    title: 'Skapa onboarding-manualer — Utbildningsmaterial från video | Manualen.nu',
    description: 'Skapa onboarding-manualer från video. Filma utbildningsmoment och dagliga rutiner — AI genererar steg-för-steg-guider för nyanställda och kompetensutveckling.',
    keywords: 'onboarding manual, utbildningsmaterial, nyanställd guide, introduktionsutbildning, utbildningsmanual generator, personalutbildning SOP',
    h1: 'Skapa onboarding-manualer',
    intro: 'Bygg utbildningsmaterial genom att filma hur uppgifter utförs. AI:n skapar visuella steg-för-steg-guider som nyanställda kan följa från dag ett — minskar uppläringstiden och säkerställer konsekvens.',
    howItWorks: [
      'Filma erfarna medarbetare som utför nyckeluppgifter',
      'Ladda upp videor — AI:n skapar utbildningsguider för varje uppgift',
      'Organisera guiderna i en introduktionssekvens',
      'Nyanställda följer visuella manualer för snabbare upplärning',
    ],
    faq: [
      { question: 'Hur snabbar det upp onboarding?', answer: 'Istället för att skugga erfarna kollegor i veckor får nyanställda visuella steg-för-steg-guider de kan följa självständigt. Företag minskar vanligtvis uppläringstiden med 50% eller mer.' },
      { question: 'Kan jag skapa ett komplett onboarding-paket?', answer: 'Ja. Filma alla nyckeluppgifter och få individuella manualer. Organisera dem i en utbildningssekvens för ett komplett onboarding-program.' },
      { question: 'Fungerar det för både fysiska och digitala uppgifter?', answer: 'Absolut. Filma handgripliga uppgifter med mobilen eller spela in skärmen för mjukvaruprocedurer. Manualen.nu hanterar båda typerna.' },
    ],
  },
  {
    slug: 'underhall',
    title: 'Skapa underhållsmanualer — Dokumentera underhållsrutiner | Manualen.nu',
    description: 'Skapa underhållsmanualer från video. Filma förebyggande underhåll, reparationer och inspektioner — AI genererar detaljerade arbetsinstruktioner med bilder.',
    keywords: 'underhåll manual, förebyggande underhåll SOP, reparationsinstruktion, underhållsrutin guide, maskindokumentation, underhållschecklista',
    h1: 'Skapa underhållsmanualer',
    intro: 'Dokumentera underhållsrutiner genom att filma dem. AI:n skapar detaljerade manualer med steg-för-steg-instruktioner, verktygskrav och visuella kontrollpunkter för förebyggande och korrektivt underhåll.',
    howItWorks: [
      'Filma underhållsproceduren — FU, reparation eller inspektion',
      'Ladda upp till Manualen.nu — AI:n delar upp i detaljerade steg',
      'Lägg till artikelnummer, intervaller och säkerhetskrav',
      'Använd som underhållsmanualer eller FU-checklistor',
    ],
    faq: [
      { question: 'Kan jag skapa förebyggande underhållschecklistor?', answer: 'Ja. Filma FU-proceduren och få en visuell checklista med inspektionspunkter, smörjningssteg och mätningar som steg med skärmbilder.' },
      { question: 'Fungerar det för komplex utrustning?', answer: 'Absolut. Manualen.nu hanterar flerstegsprocesser på komplex maskineri. AI:n upptäcker verktygsbyten, demonterings- och monteringssekvenser.' },
      { question: 'Kan jag inkludera artikelnummer och specifikationer?', answer: 'Ja. Efter att AI:n genererat grundmanualen kan du lägga till artikelnummer, åtdragningsmoment, vätskekapaciteter och andra tekniska detaljer.' },
    ],
  },
  {
    slug: 'sakerhet',
    title: 'Skapa säkerhetsutbildningsmanualer — Dokumentera säkerhetsrutiner | Manualen.nu',
    description: 'Skapa säkerhetsutbildningsmanualer från video. Filma säkerhetsrutiner, skyddsutrustning och nödprocedurer — AI genererar visuella säkerhetsguider med varningar.',
    keywords: 'säkerhetsutbildning manual, säkerhetsrutin dokumentation, skyddsutrustning guide, nödprocedur SOP, arbetsmiljö dokumentation, säkerhetsmanual generator',
    h1: 'Skapa säkerhetsutbildningsmanualer',
    intro: 'Dokumentera säkerhetsrutiner genom att filma dem. AI:n skapar visuella säkerhetsmanualer med steg-för-steg-instruktioner, krav på skyddsutrustning och säkerhetsvarningar.',
    howItWorks: [
      'Filma säkerhetsrutiner, skyddsutrustning eller nödövningar',
      'Ladda upp till Manualen.nu — AI:n identifierar varje säkerhetssteg',
      'Lägg till riskvarningar, skyddskrav och kompetenskrav',
      'Distribuera visuella säkerhetsguider till all personal',
    ],
    faq: [
      { question: 'Kan jag lägga till säkerhetsvarningar?', answer: 'Ja. Du kan lägga till fara-, varnings- och försiktighetsnoteringar till varje steg. AI:n flaggar också automatiskt steg som involverar skyddsutrustning.' },
      { question: 'Fungerar det för nödprocedurer?', answer: 'Absolut. Filma utrymningsvägar, brandsläckaranvändning, spillhantering eller första hjälpen och få tydliga visuella guider.' },
      { question: 'Kan det användas vid arbetsmiljörevisioner?', answer: 'Ja. De genererade manualerna fungerar som dokumenterad evidens för standardiserade säkerhetsrutiner och stödjer ISO- och arbetsmiljökrav.' },
    ],
  },
  {
    slug: 'video-till-manual',
    title: 'Video till manual — Förvandla vilken video som helst till en guide | Manualen.nu',
    description: 'Konvertera vilken video som helst till en professionell manual automatiskt. Ladda upp en video, AI:n upptäcker steg, fångar bilder och skapar en komplett steg-för-steg-guide.',
    keywords: 'video till manual, konvertera video till guide, skapa manual från video, video till instruktion, automatisk manual från video, video till PDF guide',
    h1: 'Video till manual — automatiskt',
    intro: 'Ladda upp vilken video som helst och få en professionell manual på minuter. AI:n tittar på videon, identifierar varje steg, fångar nyckelbilder och skriver tydliga instruktioner — timmar av dokumentationsarbete blir en enkel uppladdning.',
    howItWorks: [
      'Ladda upp valfri videofil — MP4, MOV, AVI eller andra format',
      'AI:n analyserar videon: upptäcker steg, fångar bilder, transkriberar ljud',
      'Granska den autogenererade manualen med steg-för-steg-instruktioner',
      'Exportera som PDF eller dela digitalt med ditt team',
    ],
    faq: [
      { question: 'Vilka videoformat stöds?', answer: 'Manualen.nu stödjer alla vanliga videoformat inklusive MP4, MOV, AVI och WebM. Du kan också klistra in en YouTube-URL.' },
      { question: 'Hur träffsäker är stegdetekteringen?', answer: 'AI:n använder avancerad scendetektering och ljudanalys för att identifiera steg med hög träffsäkerhet. Du kan alltid justera, dela eller slå ihop steg i redigeraren.' },
      { question: 'Kan jag redigera den genererade manualen?', answer: 'Ja. AI:n skapar ett komplett första utkast som du kan redigera — ändra text, ordna om steg, lägg till eller ta bort bilder och infoga varningar.' },
    ],
  },
];
