import React from 'react';
import { AppView } from '../types';

interface TermsPageProps {
  onNavigate: (view: AppView) => void;
}

const TermsPage: React.FC<TermsPageProps> = ({ onNavigate }) => {
  return (
    <div className="min-h-screen bg-white">
      {/* Navigation */}
      <nav className="fixed top-0 left-0 right-0 bg-white/80 backdrop-blur-md z-50 border-b border-slate-100">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <div
              className="flex items-center gap-3 cursor-pointer"
              onClick={() => onNavigate(AppView.LANDING)}
            >
              <div className="w-11 h-11 rounded-xl flex items-center justify-center">
                <img src="/logo.png" alt="FrameOps" className="w-11 h-11" />
              </div>
              <span className="font-bold text-xl text-slate-900">FrameOps</span>
            </div>
            <button
              onClick={() => onNavigate(AppView.LANDING)}
              className="text-slate-600 hover:text-slate-900 font-medium"
            >
              <i className="fas fa-arrow-left mr-2"></i>
              Back to Home
            </button>
          </div>
        </div>
      </nav>

      {/* Content */}
      <div className="pt-24 pb-16 px-4 sm:px-6 lg:px-8">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-4xl font-bold text-slate-900 mb-8">Terms of Service</h1>
          <p className="text-slate-500 mb-8">Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>

          <div className="prose prose-slate max-w-none">
            <section className="mb-8">
              <h2 className="text-2xl font-bold text-slate-900 mb-4">1. Acceptance of Terms</h2>
              <p className="text-slate-600 mb-4">
                By accessing or using FrameOps ("Service"), you agree to be bound by these Terms of Service.
                If you do not agree to these terms, please do not use the Service.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-slate-900 mb-4">2. Description of Service</h2>
              <p className="text-slate-600 mb-4">
                FrameOps is an AI-powered service that converts videos into Standard Operating Procedures (SOPs)
                and step-by-step guides. The Service analyzes video content and generates documentation based
                on the visual and audio content provided.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-slate-900 mb-4">3. User Responsibilities</h2>
              <p className="text-slate-600 mb-4">You agree to:</p>
              <ul className="list-disc pl-6 text-slate-600 space-y-2">
                <li>Provide accurate information when creating an account</li>
                <li>Only upload videos you have the right to use</li>
                <li>Not use the Service for illegal purposes</li>
                <li>Not attempt to circumvent any security measures</li>
                <li>Not share your account credentials with others</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-slate-900 mb-4">4. Content Ownership</h2>
              <p className="text-slate-600 mb-4">
                <strong>Your Content:</strong> You retain ownership of all videos you upload and SOPs you create.
                By using the Service, you grant us a limited license to process your content solely for the
                purpose of providing the Service.
              </p>
              <p className="text-slate-600 mb-4">
                <strong>Generated Content:</strong> SOPs and documentation generated by our AI are derived from
                your source content. You own the generated output and may use it for any legal purpose.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-slate-900 mb-4">5. Acceptable Use</h2>
              <p className="text-slate-600 mb-4">You may not use the Service to:</p>
              <ul className="list-disc pl-6 text-slate-600 space-y-2">
                <li>Process content that infringes on others' intellectual property rights</li>
                <li>Generate harmful, illegal, or misleading content</li>
                <li>Violate any applicable laws or regulations</li>
                <li>Harass, abuse, or harm others</li>
                <li>Distribute malware or engage in phishing</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-slate-900 mb-4">6. Payment and Subscriptions</h2>
              <p className="text-slate-600 mb-4">
                Paid subscriptions are billed according to the plan selected. You may cancel your subscription
                at any time, and you will continue to have access until the end of your billing period.
                Refunds are handled on a case-by-case basis.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-slate-900 mb-4">7. Disclaimer of Warranties</h2>
              <p className="text-slate-600 mb-4">
                The Service is provided "as is" without warranties of any kind. While we strive for accuracy,
                AI-generated content should be reviewed and verified before use in critical applications.
                We do not guarantee that the Service will be uninterrupted or error-free.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-slate-900 mb-4">8. Limitation of Liability</h2>
              <p className="text-slate-600 mb-4">
                To the maximum extent permitted by law, FrameOps shall not be liable for any indirect,
                incidental, special, or consequential damages arising from your use of the Service.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-slate-900 mb-4">9. Changes to Terms</h2>
              <p className="text-slate-600 mb-4">
                We may update these terms from time to time. We will notify you of significant changes
                via email or through the Service. Continued use after changes constitutes acceptance
                of the updated terms.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-slate-900 mb-4">10. Contact</h2>
              <p className="text-slate-600 mb-4">
                For questions about these Terms of Service, please contact us at:
              </p>
              <p className="text-slate-600">
                <strong>Email:</strong> <a href="mailto:support@frameops.ai" className="text-indigo-600 hover:underline">support@frameops.ai</a>
              </p>
            </section>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="py-8 px-4 border-t border-slate-100">
        <div className="max-w-7xl mx-auto text-center">
          <p className="text-slate-500 text-sm">
            &copy; {new Date().getFullYear()} FrameOps. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
};

export default TermsPage;
